---
- name: Deploy Microservice Application
  hosts: webservers
  become: yes

  vars:
    app_repo_url: "{{ lookup('env', 'GITHUB_REPO_URL') or 'https://github.com/AzizSoftware/SSAFT_DEPLOYMENT_PIPELINE.git' }}"
    app_dir_on_vm: "/home/azureuser/my-microservice-app"
    docker_compose_file: "{{ app_dir_on_vm }}/SSATF/docker-compose.yml"

  tasks:
   
    - name: Wait for SSH connection and cloud-init to finish (up to 300 seconds)
      ansible.builtin.wait_for_connection:
        delay: 10 # Délai initial avant la première vérification
        timeout: 300 # Temps total maximum d'attente
        sleep: 10 # Intervalle entre les vérifications
    - name: Wait for cloud-init to finish completely (max 360 sec)
      ansible.builtin.shell: |
        while [ "$(cloud-init status --wait 2>/dev/null)" != "status: done" ]; do
          sleep 5
        done
      changed_when: false


    - name: Ensure Git is installed (in case cloud-init missed it)
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Check if azureuser is in docker group
      ansible.builtin.shell: groups azureuser | grep -q docker
      register: docker_group_check
      changed_when: false
      failed_when: false

    - name: Add azureuser to docker group if not already in it
      ansible.builtin.user:
        name: azureuser
        groups: docker
        append: yes
      when: docker_group_check.rc != 0
      notify: Reload SSH connection

    - name: Ensure application directory exists
      ansible.builtin.file:
        path: "{{ app_dir_on_vm }}"
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Clone or update application repo
      ansible.builtin.git:
        repo: "{{ app_repo_url }}"
        dest: "{{ app_dir_on_vm }}"
        version: main
        accept_hostkey: yes
        force: yes
      become_user: azureuser

    - name: Fix permissions for app directory
      ansible.builtin.file:
        path: "{{ app_dir_on_vm }}"
        state: directory
        owner: azureuser
        group: azureuser
        recurse: yes
        mode: '0755'

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker SDK for Python is installed
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: yes

    - name: Ensure docker-compose Python module is installed
      ansible.builtin.pip:
        name: docker-compose
        executable: pip3

    - name: Launch services via Docker Compose
      community.docker.docker_compose:
        project_src: "{{ app_dir_on_vm }}/SSATF"
        files:
          - docker-compose.yml
        build: yes
        state: present

  handlers:
    - name: Reload SSH connection
      meta: reset_connection
